pub type AtlasColorRgb = [u8; 3];

#[derive(Debug, Clone, Copy)]
pub struct AtlasTuning {
    pub normalization: AtlasNormalizationTuning,
    pub continent: AtlasContinentTuning,
    pub ridge: AtlasRidgeTuning,
    pub terrain: AtlasTerrainTuning,
    pub climate: AtlasClimateTuning,
    pub hydrology: AtlasHydrologyTuning,
    pub weights: AtlasWeightTuning,
    pub resolver: AtlasResolverTuning,
    pub preview: AtlasPreviewDebugTuning,
}

impl Default for AtlasTuning {
    fn default() -> Self {
        Self {
            normalization: AtlasNormalizationTuning::default(),
            continent: AtlasContinentTuning::default(),
            ridge: AtlasRidgeTuning::default(),
            terrain: AtlasTerrainTuning::default(),
            climate: AtlasClimateTuning::default(),
            hydrology: AtlasHydrologyTuning::default(),
            weights: AtlasWeightTuning::default(),
            resolver: AtlasResolverTuning::default(),
            preview: AtlasPreviewDebugTuning::default(),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasNormalizationTuning {
    /// Authoritative land/ocean split used by atlas generation and preview.
    pub land_threshold: f32,
    pub ocean_distance_normalizer: f32,
    pub coast_distance_normalizer: f32,
    pub continent_core_normalizer: f32,
    pub coast_factor_distance: f32,
    pub river_distance_normalizer: f32,
    pub ridge_landness_min: f32,
    pub ridge_landness_max: f32,
}

impl Default for AtlasNormalizationTuning {
    fn default() -> Self {
        Self {
            land_threshold: 0.53,
            ocean_distance_normalizer: 24.0,
            coast_distance_normalizer: 12.0,
            continent_core_normalizer: 22.0,
            coast_factor_distance: 3.0,
            river_distance_normalizer: 10.0,
            ridge_landness_min: 0.35,
            ridge_landness_max: 0.95,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasContinentTuning {
    pub warp_scale: f64,
    pub warp_amplitude: f64,
    pub primary_scale: f64,
    pub primary_octaves: u32,
    pub primary_lacunarity: f64,
    pub primary_gain: f32,
    pub secondary_scale: f64,
    pub secondary_octaves: u32,
    pub secondary_lacunarity: f64,
    pub secondary_gain: f32,
    pub island_scale: f64,
    pub island_octaves: u32,
    pub island_lacunarity: f64,
    pub island_gain: f32,
    pub coast_scale: f64,
    pub coast_octaves: u32,
    pub coast_lacunarity: f64,
    pub coast_gain: f32,
    pub primary_weight: f32,
    pub secondary_weight: f32,
    pub island_weight: f32,
    pub coast_penalty: f32,
    pub bias: f32,
}

impl Default for AtlasContinentTuning {
    fn default() -> Self {
        Self {
            warp_scale: 1.0 / 96.0,
            warp_amplitude: 6.5,
            primary_scale: 200.0,
            primary_octaves: 5,
            primary_lacunarity: 2.0,
            primary_gain: 0.55,
            secondary_scale: 48.0,
            secondary_octaves: 4,
            secondary_lacunarity: 2.1,
            secondary_gain: 0.55,
            island_scale: 14.0,
            island_octaves: 3,
            island_lacunarity: 2.0,
            island_gain: 0.5,
            coast_scale: 20.0,
            coast_octaves: 4,
            coast_lacunarity: 2.0,
            coast_gain: 0.55,
            primary_weight: 0.62,
            secondary_weight: 0.26,
            island_weight: 0.12,
            coast_penalty: 0.18,
            bias: 0.15,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasRidgeTuning {
    pub warp_scale: f64,
    pub warp_amplitude: f64,
    pub primary_scale: f64,
    pub primary_octaves: u32,
    pub primary_lacunarity: f64,
    pub primary_gain: f32,
    pub secondary_scale: f64,
    pub secondary_octaves: u32,
    pub secondary_lacunarity: f64,
    pub secondary_gain: f32,
    pub primary_weight: f32,
    pub secondary_weight: f32,
}

impl Default for AtlasRidgeTuning {
    fn default() -> Self {
        Self {
            warp_scale: 1.0 / 18.0,
            warp_amplitude: 2.6,
            primary_scale: 30.0,
            primary_octaves: 5,
            primary_lacunarity: 2.03,
            primary_gain: 0.53,
            secondary_scale: 42.0,
            secondary_octaves: 3,
            secondary_lacunarity: 2.0,
            secondary_gain: 0.5,
            primary_weight: 1.00,
            secondary_weight: 0.28,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasTerrainTuning {
    pub macro_base_height: f32,
    pub macro_landness_weight: f32,
    pub macro_continent_core_weight: f32,
    pub macro_mountain_weight: f32,
    pub macro_coast_penalty: f32,
    pub macro_ocean_floor_scale: f32,
    pub detail_scale: f64,
    pub detail_octaves: u32,
    pub detail_lacunarity: f64,
    pub detail_gain: f32,
    pub slope_scale: f32,
    pub rugged_ridge_weight: f32,
    pub rugged_slope_weight: f32,
    pub rugged_detail_weight: f32,
    pub basin_offset: f32,
    pub basin_scale: f32,
    pub pass_ridge_penalty: f32,
    pub pass_slope_penalty: f32,
    pub pass_mean_diff_weight: f32,
    pub mountain_cluster_scale: f64,
    pub mountain_cluster_octaves: u32,
    pub mountain_cluster_lacunarity: f64,
    pub mountain_cluster_gain: f32,
    pub mountain_ridge_weight: f32,
    pub mountain_cluster_weight: f32,
    pub mountain_base_min: f32,
    pub mountain_base_max: f32,
    pub mountain_continent_min: f32,
    pub mountain_continent_max: f32,
    pub mountain_landness_bias: f32,
}

impl Default for AtlasTerrainTuning {
    fn default() -> Self {
        Self {
            macro_base_height: 0.06,
            macro_landness_weight: 0.18,
            macro_continent_core_weight: 0.42,
            macro_mountain_weight: 0.34,
            macro_coast_penalty: 0.08,
            macro_ocean_floor_scale: 0.08,
            detail_scale: 12.0,
            detail_octaves: 3,
            detail_lacunarity: 2.0,
            detail_gain: 0.5,
            slope_scale: 3.25,
            rugged_ridge_weight: 0.52,
            rugged_slope_weight: 0.33,
            rugged_detail_weight: 0.15,
            basin_offset: 0.05,
            basin_scale: 4.0,
            pass_ridge_penalty: 0.68,
            pass_slope_penalty: 0.45,
            pass_mean_diff_weight: 0.25,
            mountain_cluster_scale: 40.0,
            mountain_cluster_octaves: 4,
            mountain_cluster_lacunarity: 2.0,
            mountain_cluster_gain: 0.52,
            mountain_ridge_weight: 0.96,
            mountain_cluster_weight: 0.48,
            mountain_base_min: 0.22,
            mountain_base_max: 0.48,
            mountain_continent_min: 0.04,
            mountain_continent_max: 0.22,
            mountain_landness_bias: 0.35,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasClimateTuning {
    pub temperature_field_scale: f64,
    pub temperature_octaves: u32,
    pub temperature_lacunarity: f64,
    pub temperature_gain: f32,
    pub humidity_field_scale: f64,
    pub humidity_octaves: u32,
    pub humidity_lacunarity: f64,
    pub humidity_gain: f32,
    pub equator_falloff_scale: f32,
    pub temperature_equator_weight: f32,
    pub temperature_noise_weight: f32,
    pub temperature_elevation_cooling: f32,
    pub temperature_mountain_cooling: f32,
    pub polar_edge_warm: f32,
    pub polar_edge_cold: f32,
    pub humidity_noise_weight: f32,
    pub humidity_ocean_bonus: f32,
    pub humidity_basin_bonus: f32,
    pub humidity_inland_penalty: f32,
    pub humidity_rain_shadow_penalty: f32,
    pub humidity_river_bonus: f32,
    pub humidity_lake_bonus: f32,
}

impl Default for AtlasClimateTuning {
    fn default() -> Self {
        Self {
            temperature_field_scale: 64.0,
            temperature_octaves: 4,
            temperature_lacunarity: 2.0,
            temperature_gain: 0.5,
            humidity_field_scale: 48.0,
            humidity_octaves: 5,
            humidity_lacunarity: 2.0,
            humidity_gain: 0.5,
            equator_falloff_scale: 320.0,
            temperature_equator_weight: 0.62,
            temperature_noise_weight: 0.38,
            temperature_elevation_cooling: 0.46,
            temperature_mountain_cooling: 0.08,
            polar_edge_warm: 0.18,
            polar_edge_cold: 0.02,
            humidity_noise_weight: 0.52,
            humidity_ocean_bonus: 0.32,
            humidity_basin_bonus: 0.16,
            humidity_inland_penalty: 0.26,
            humidity_rain_shadow_penalty: 0.18,
            humidity_river_bonus: 0.18,
            humidity_lake_bonus: 0.08,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasHydrologyTuning {
    pub river_source_mountain_weight: f32,
    pub river_source_humidity_weight: f32,
    pub river_source_slope_weight: f32,
    pub flow_base: f32,
    pub flow_humidity_weight: f32,
    pub flow_mountain_weight: f32,
    pub flow_cold_weight: f32,
    pub river_threshold: f32,
    pub river_source_threshold: f32,
    pub river_override_threshold: f32,
    pub river_min_macro_elevation: f32,
    pub lake_basin_weight: f32,
    pub lake_flow_weight: f32,
    pub lake_sink_bonus: f32,
    pub lake_flat_bonus: f32,
    pub lake_threshold: f32,
    pub lake_min_macro_elevation: f32,
    pub lake_max_slope: f32,
    pub riverine_distance_weight: f32,
    pub riverine_flow_weight: f32,
    pub wetness_humidity_weight: f32,
    pub wetness_river_weight: f32,
    pub wetness_lake_weight: f32,
    pub wetness_basin_weight: f32,
    pub aridity_dryness_weight: f32,
    pub aridity_inland_weight: f32,
    pub aridity_low_wetness_weight: f32,
    pub aridity_river_relief: f32,
    pub alpine_elevation_min: f32,
    pub alpine_elevation_max: f32,
    pub alpine_elevation_weight: f32,
    pub alpine_mountain_min: f32,
    pub alpine_mountain_max: f32,
    pub alpine_mountain_weight: f32,
    pub alpine_polar_penalty: f32,
    pub wetland_wetness_weight: f32,
    pub wetland_basin_weight: f32,
    pub wetland_river_weight: f32,
    pub wetland_slope_penalty: f32,
}

impl Default for AtlasHydrologyTuning {
    fn default() -> Self {
        Self {
            river_source_mountain_weight: 0.42,
            river_source_humidity_weight: 0.34,
            river_source_slope_weight: 0.24,
            flow_base: 0.12,
            flow_humidity_weight: 0.58,
            flow_mountain_weight: 0.20,
            flow_cold_weight: 0.10,
            river_threshold: 0.033,
            river_source_threshold: 0.28,
            river_override_threshold: 0.10,
            river_min_macro_elevation: 0.10,
            lake_basin_weight: 0.54,
            lake_flow_weight: 0.26,
            lake_sink_bonus: 0.20,
            lake_flat_bonus: 0.10,
            lake_threshold: 0.62,
            lake_min_macro_elevation: 0.08,
            lake_max_slope: 0.45,
            riverine_distance_weight: 0.74,
            riverine_flow_weight: 0.26,
            wetness_humidity_weight: 0.55,
            wetness_river_weight: 0.25,
            wetness_lake_weight: 0.10,
            wetness_basin_weight: 0.10,
            aridity_dryness_weight: 0.60,
            aridity_inland_weight: 0.30,
            aridity_low_wetness_weight: 0.10,
            aridity_river_relief: 0.15,
            alpine_elevation_min: 0.44,
            alpine_elevation_max: 0.66,
            alpine_elevation_weight: 0.45,
            alpine_mountain_min: 0.14,
            alpine_mountain_max: 0.42,
            alpine_mountain_weight: 0.55,
            alpine_polar_penalty: 0.10,
            wetland_wetness_weight: 0.45,
            wetland_basin_weight: 0.35,
            wetland_river_weight: 0.20,
            wetland_slope_penalty: 0.25,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasWeightTuning {
    pub thermal_centers: [f32; 5],
    pub thermal_widths: [f32; 5],
    pub moisture_signal_humidity_weight: f32,
    pub moisture_signal_wetness_weight: f32,
    pub moisture_signal_aridity_penalty: f32,
    pub moisture_signal_bias: f32,
    pub moisture_centers: [f32; 5],
    pub moisture_widths: [f32; 5],
    pub moisture_arid_boost: f32,
    pub moisture_wet_boost: f32,
    pub form_mountain_min: f32,
    pub form_mountain_max: f32,
    pub form_mountain_mass_weight: f32,
    pub form_mountain_ruggedness_weight: f32,
    pub form_hill_min: f32,
    pub form_hill_max: f32,
    pub form_hill_macro_elevation_weight: f32,
    pub form_hill_mountain_suppression: f32,
    pub form_plain_mountain_penalty: f32,
    pub form_plain_hill_penalty: f32,
    pub cover_canopy_humidity_weight: f32,
    pub cover_canopy_wetness_weight: f32,
    pub cover_canopy_temperate_weight: f32,
    pub cover_canopy_warm_bonus_weight: f32,
    pub cover_canopy_aridity_penalty: f32,
    pub cover_canopy_alpine_penalty: f32,
    pub cover_forest_canopy_weight: f32,
    pub cover_forest_river_weight: f32,
    pub cover_forest_humid_weight: f32,
    pub cover_openness_base: f32,
    pub cover_openness_aridity_weight: f32,
    pub cover_openness_plain_weight: f32,
    pub cover_openness_canopy_penalty: f32,
    pub cover_openness_wet_penalty: f32,
    pub cover_grass_openness_weight: f32,
    pub cover_grass_subhumid_weight: f32,
    pub cover_grass_humid_weight: f32,
    pub cover_grass_temperate_weight: f32,
    pub cover_shrub_aridity_weight: f32,
    pub cover_shrub_semi_arid_weight: f32,
    pub cover_shrub_hill_weight: f32,
    pub cover_shrub_bias: f32,
    pub ecotone_thermal_weight: f32,
    pub ecotone_moisture_weight: f32,
    pub ecotone_overlay_weight: f32,
}

impl Default for AtlasWeightTuning {
    fn default() -> Self {
        Self {
            thermal_centers: [0.04, 0.22, 0.50, 0.72, 0.92],
            thermal_widths: [0.18, 0.22, 0.24, 0.22, 0.18],
            moisture_signal_humidity_weight: 0.72,
            moisture_signal_wetness_weight: 0.18,
            moisture_signal_aridity_penalty: 0.20,
            moisture_signal_bias: 0.15,
            moisture_centers: [0.06, 0.24, 0.50, 0.74, 0.94],
            moisture_widths: [0.16, 0.20, 0.24, 0.20, 0.16],
            moisture_arid_boost: 0.72,
            moisture_wet_boost: 0.72,
            form_mountain_min: 0.54,
            form_mountain_max: 0.78,
            form_mountain_mass_weight: 0.68,
            form_mountain_ruggedness_weight: 0.32,
            form_hill_min: 0.24,
            form_hill_max: 0.52,
            form_hill_macro_elevation_weight: 0.18,
            form_hill_mountain_suppression: 0.60,
            form_plain_mountain_penalty: 0.85,
            form_plain_hill_penalty: 0.55,
            cover_canopy_humidity_weight: 0.44,
            cover_canopy_wetness_weight: 0.20,
            cover_canopy_temperate_weight: 0.20,
            cover_canopy_warm_bonus_weight: 0.35,
            cover_canopy_aridity_penalty: 0.34,
            cover_canopy_alpine_penalty: 0.20,
            cover_forest_canopy_weight: 0.70,
            cover_forest_river_weight: 0.15,
            cover_forest_humid_weight: 0.15,
            cover_openness_base: 0.45,
            cover_openness_aridity_weight: 0.25,
            cover_openness_plain_weight: 0.15,
            cover_openness_canopy_penalty: 0.35,
            cover_openness_wet_penalty: 0.10,
            cover_grass_openness_weight: 0.45,
            cover_grass_subhumid_weight: 0.20,
            cover_grass_humid_weight: 0.15,
            cover_grass_temperate_weight: 0.10,
            cover_shrub_aridity_weight: 0.35,
            cover_shrub_semi_arid_weight: 0.25,
            cover_shrub_hill_weight: 0.15,
            cover_shrub_bias: 0.15,
            ecotone_thermal_weight: 0.40,
            ecotone_moisture_weight: 0.40,
            ecotone_overlay_weight: 0.20,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasResolverTuning {
    /// Minimum overlay strength before preview uses overlay-driven biomes.
    pub overlay_min_strength: f32,
    pub alpine_form_threshold: f32,
    pub coast_mountain_cap: f32,
    pub riverplain_wetness_threshold: f32,
    pub forest_threshold: f32,
    pub grass_threshold: f32,
}

impl Default for AtlasResolverTuning {
    fn default() -> Self {
        Self {
            overlay_min_strength: 0.34,
            alpine_form_threshold: 0.48,
            coast_mountain_cap: 0.45,
            riverplain_wetness_threshold: 0.40,
            forest_threshold: 0.60,
            grass_threshold: 0.52,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct AtlasPreviewDebugTuning {
    pub ocean_depth_coast_weight: f32,
    pub ocean_depth_landness_weight: f32,
    pub land_height_macro_weight: f32,
    pub land_height_mountain_weight: f32,
    pub land_height_ruggedness_weight: f32,
    pub land_height_alpine_weight: f32,
    pub land_height_coast_penalty: f32,
    pub mountain_range_ridge_weight: f32,
    pub mountain_range_mass_weight: f32,
    pub mountain_range_form_weight: f32,
    pub mountain_range_threshold: f32,
    pub mountain_range_strength: f32,
    pub ocean_light: AtlasColorRgb,
    pub ocean_dark: AtlasColorRgb,
    pub ocean_shade_strength: f32,
    pub coast_light: AtlasColorRgb,
    pub coast_dark: AtlasColorRgb,
    pub coast_shade_strength: f32,
    pub polar_light: AtlasColorRgb,
    pub polar_dark: AtlasColorRgb,
    pub polar_shade_strength: f32,
    pub desert_light: AtlasColorRgb,
    pub desert_dark: AtlasColorRgb,
    pub desert_shade_strength: f32,
    pub wetland_light: AtlasColorRgb,
    pub wetland_dark: AtlasColorRgb,
    pub wetland_shade_strength: f32,
    pub riverplain_light: AtlasColorRgb,
    pub riverplain_dark: AtlasColorRgb,
    pub riverplain_shade_strength: f32,
    pub alpine_light: AtlasColorRgb,
    pub alpine_dark: AtlasColorRgb,
    pub alpine_shade_strength: f32,
    pub mountain_light: AtlasColorRgb,
    pub mountain_dark: AtlasColorRgb,
    pub mountain_shade_strength: f32,
    pub steppe_light: AtlasColorRgb,
    pub steppe_dark: AtlasColorRgb,
    pub steppe_shade_strength: f32,
    pub grassland_light: AtlasColorRgb,
    pub grassland_dark: AtlasColorRgb,
    pub grassland_shade_strength: f32,
    pub temperate_forest_light: AtlasColorRgb,
    pub temperate_forest_dark: AtlasColorRgb,
    pub temperate_forest_shade_strength: f32,
    pub boreal_forest_light: AtlasColorRgb,
    pub boreal_forest_dark: AtlasColorRgb,
    pub boreal_forest_shade_strength: f32,
    pub tropical_forest_light: AtlasColorRgb,
    pub tropical_forest_dark: AtlasColorRgb,
    pub tropical_forest_shade_strength: f32,
    pub river_tint: AtlasColorRgb,
    pub river_tint_threshold: f32,
    pub river_tint_strength: f32,
}

impl Default for AtlasPreviewDebugTuning {
    fn default() -> Self {
        Self {
            ocean_depth_coast_weight: 0.72,
            ocean_depth_landness_weight: 0.28,
            land_height_macro_weight: 0.56,
            land_height_mountain_weight: 0.40,
            land_height_ruggedness_weight: 0.12,
            land_height_alpine_weight: 0.06,
            land_height_coast_penalty: 0.22,
            mountain_range_ridge_weight: 1.00,
            mountain_range_mass_weight: 0.80,
            mountain_range_form_weight: 0.20,
            mountain_range_threshold: 0.20,
            mountain_range_strength: 3.99,
            ocean_light: [106, 176, 232],
            ocean_dark: [8, 38, 102],
            ocean_shade_strength: 0.88,
            coast_light: [244, 232, 176],
            coast_dark: [214, 196, 126],
            coast_shade_strength: 0.52,
            polar_light: [250, 250, 246],
            polar_dark: [214, 222, 228],
            polar_shade_strength: 0.40,
            desert_light: [238, 150, 64],
            desert_dark: [166, 88, 26],
            desert_shade_strength: 0.62,
            wetland_light: [82, 138, 98],
            wetland_dark: [40, 86, 66],
            wetland_shade_strength: 0.70,
            riverplain_light: [98, 164, 114],
            riverplain_dark: [48, 98, 78],
            riverplain_shade_strength: 0.60,
            alpine_light: [126, 156, 134],
            alpine_dark: [62, 94, 78],
            alpine_shade_strength: 0.78,
            mountain_light: [92, 138, 82],
            mountain_dark: [28, 62, 32],
            mountain_shade_strength: 0.86,
            steppe_light: [142, 156, 92],
            steppe_dark: [78, 96, 40],
            steppe_shade_strength: 0.66,
            grassland_light: [112, 172, 92],
            grassland_dark: [44, 96, 34],
            grassland_shade_strength: 0.68,
            temperate_forest_light: [74, 136, 72],
            temperate_forest_dark: [20, 58, 24],
            temperate_forest_shade_strength: 0.76,
            boreal_forest_light: [72, 118, 94],
            boreal_forest_dark: [26, 56, 42],
            boreal_forest_shade_strength: 0.74,
            tropical_forest_light: [46, 154, 82],
            tropical_forest_dark: [12, 68, 30],
            tropical_forest_shade_strength: 0.72,
            river_tint: [70, 142, 186],
            river_tint_threshold: 0.56,
            river_tint_strength: 0.18,
        }
    }
}
