#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MaterialPolicyId {
    OceanicShelf,
    SandyBeach,
    SteppeGrassland,
    SavannaGrassland,
    TemperateGrassland,
    TemperatePlateau,
    TropicalLowland,
    TropicalHills,
    DesertSurface,
    ColdWetland,
    AlpineExposed,
    TundraExposure,
    CoastalCliff,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MaterialPolicyDef {
    pub id: MaterialPolicyId,
    pub summary: &'static str,
    pub top_cover_hint: &'static str,
    pub subsoil_hint: &'static str,
    pub sediment_override_hint: &'static str,
    pub default_top_block: &'static str,
    pub dry_top_block: &'static str,
    pub wet_top_block: &'static str,
    pub frozen_top_block: &'static str,
    pub subsoil_block: &'static str,
    pub deep_block: &'static str,
    pub exposed_block: &'static str,
    pub sediment_block: &'static str,
}

pub const MATERIAL_POLICIES: &[MaterialPolicyDef] = &[
    MaterialPolicyDef {
        id: MaterialPolicyId::OceanicShelf,
        summary: "Submerged shelf and shallow marine sediment policy anchored around sand, silt, and stone.",
        top_cover_hint: "sand_or_silt",
        subsoil_hint: "silt_or_clay",
        sediment_override_hint: "connected marine water stays authoritative through sea-level fill.",
        default_top_block: "sand",
        dry_top_block: "sand",
        wet_top_block: "silt",
        frozen_top_block: "ice",
        subsoil_block: "silt",
        deep_block: "stone",
        exposed_block: "stone",
        sediment_block: "silt",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::SandyBeach,
        summary: "Beach and barrier surface policy centered on dry and wet sand over firmer coastal support.",
        top_cover_hint: "sand",
        subsoil_hint: "sand",
        sediment_override_hint: "intertidal strips can flip to wet sand, silt, or gravel through hydrology and coast context.",
        default_top_block: "sand",
        dry_top_block: "sand",
        wet_top_block: "wet_sand",
        frozen_top_block: "snow",
        subsoil_block: "sand",
        deep_block: "stone",
        exposed_block: "stone",
        sediment_block: "silt",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::SteppeGrassland,
        summary: "Dry grass and coarse soil policy for steppe and transition dryland plains.",
        top_cover_hint: "dry_grass",
        subsoil_hint: "dirt_or_coarse_dirt",
        sediment_override_hint: "drain lines may expose gravel, silt, or mud locally.",
        default_top_block: "dry_grass",
        dry_top_block: "coarse_dirt",
        wet_top_block: "mud",
        frozen_top_block: "snow",
        subsoil_block: "dirt",
        deep_block: "stone",
        exposed_block: "gravel",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::SavannaGrassland,
        summary: "Dry-season grass and soil policy for savanna-like launch surfaces.",
        top_cover_hint: "dry_grass",
        subsoil_hint: "dirt",
        sediment_override_hint: "wet-season and channel margins can expose greener cover or damp sediment.",
        default_top_block: "dry_grass",
        dry_top_block: "dry_grass",
        wet_top_block: "grass",
        frozen_top_block: "dry_grass",
        subsoil_block: "dirt",
        deep_block: "stone",
        exposed_block: "exposed_rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::TemperateGrassland,
        summary: "Default grass-over-dirt policy for temperate plains and gentle hills.",
        top_cover_hint: "grass",
        subsoil_hint: "dirt",
        sediment_override_hint: "river and lake materials override through hydrology.",
        default_top_block: "grass",
        dry_top_block: "coarse_dirt",
        wet_top_block: "mud",
        frozen_top_block: "snow",
        subsoil_block: "dirt",
        deep_block: "stone",
        exposed_block: "exposed_rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::TemperatePlateau,
        summary: "Grass and dirt policy with higher rock exposure on edges and stronger slopes.",
        top_cover_hint: "grass_or_sparse_grass",
        subsoil_hint: "dirt_with_rock_exposure",
        sediment_override_hint: "terrace shoulders may expose more stone later.",
        default_top_block: "grass",
        dry_top_block: "coarse_dirt",
        wet_top_block: "mud",
        frozen_top_block: "snow",
        subsoil_block: "dirt",
        deep_block: "stone",
        exposed_block: "exposed_rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::TropicalLowland,
        summary: "Dense warm-soil surface policy for rainforest and tropical wet lowlands.",
        top_cover_hint: "jungle_grass_or_litter",
        subsoil_hint: "rich_dirt",
        sediment_override_hint: "wet pockets can transition to mud through hydrology.",
        default_top_block: "jungle_grass",
        dry_top_block: "laterite",
        wet_top_block: "mud",
        frozen_top_block: "mud",
        subsoil_block: "humus",
        deep_block: "dirt",
        exposed_block: "laterite",
        sediment_block: "silt",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::TropicalHills,
        summary: "Humus and litter policy for tropical hills with stronger rock exposure and laterite on stressed slopes.",
        top_cover_hint: "jungle_grass_or_humus",
        subsoil_hint: "humus_over_stone",
        sediment_override_hint: "steeper wet corridors can reveal gravel, mud, or exposed rock later.",
        default_top_block: "jungle_grass",
        dry_top_block: "laterite",
        wet_top_block: "mud",
        frozen_top_block: "mud",
        subsoil_block: "humus",
        deep_block: "stone",
        exposed_block: "exposed_rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::DesertSurface,
        summary: "Sand-dominant surface with sparse moist exceptions.",
        top_cover_hint: "sand",
        subsoil_hint: "packed_sand",
        sediment_override_hint: "runoff corridors can reveal gravel or mud locally.",
        default_top_block: "sand",
        dry_top_block: "red_sand",
        wet_top_block: "wet_sand",
        frozen_top_block: "sand",
        subsoil_block: "sand",
        deep_block: "sandstone",
        exposed_block: "exposed_rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::ColdWetland,
        summary: "Wet soil and marshy surface policy with strong freeze-thaw response.",
        top_cover_hint: "wet_grass_or_mud",
        subsoil_hint: "soft_dirt",
        sediment_override_hint: "winter can freeze exposed mud or shallow water edges.",
        default_top_block: "mud",
        dry_top_block: "dirt",
        wet_top_block: "peat",
        frozen_top_block: "snow",
        subsoil_block: "clay",
        deep_block: "dirt",
        exposed_block: "gravel",
        sediment_block: "silt",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::AlpineExposed,
        summary: "Rock-forward surface with snow persistence and sparse cover.",
        top_cover_hint: "snow_or_exposed_rock",
        subsoil_hint: "thin_soil",
        sediment_override_hint: "melt channels can introduce gravel and wet rock later.",
        default_top_block: "scree",
        dry_top_block: "exposed_rock",
        wet_top_block: "gravel",
        frozen_top_block: "snow",
        subsoil_block: "moraine",
        deep_block: "stone",
        exposed_block: "rock",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::TundraExposure,
        summary: "Cold sparse-soil policy with thin organic cover, gravel, and persistent seasonal snow pressure.",
        top_cover_hint: "thin_soil_or_moss",
        subsoil_hint: "dirt",
        sediment_override_hint: "cold wet pockets may freeze or expose gravel before deeper soil changes.",
        default_top_block: "thin_soil",
        dry_top_block: "gravel",
        wet_top_block: "moss",
        frozen_top_block: "snow",
        subsoil_block: "dirt",
        deep_block: "stone",
        exposed_block: "gravel",
        sediment_block: "gravel",
    },
    MaterialPolicyDef {
        id: MaterialPolicyId::CoastalCliff,
        summary: "Rock and sparse-soil coast policy with shoreline sediment overrides.",
        top_cover_hint: "sparse_grass_or_rock",
        subsoil_hint: "thin_dirt_over_stone",
        sediment_override_hint: "shoreline and pocket beaches override through coast policy.",
        default_top_block: "gravel",
        dry_top_block: "gravel",
        wet_top_block: "wet_gravel",
        frozen_top_block: "snow",
        subsoil_block: "gravel",
        deep_block: "stone",
        exposed_block: "rock",
        sediment_block: "wet_gravel",
    },
];

pub fn default_material_policies() -> &'static [MaterialPolicyDef] {
    MATERIAL_POLICIES
}

pub fn material_policy_def(id: MaterialPolicyId) -> Option<&'static MaterialPolicyDef> {
    MATERIAL_POLICIES.iter().find(|policy| policy.id == id)
}
