id = 35
key = "boreal_taiga_conifer_leaves"
solid = true
opaque = false
render = "cube"
material = "foliage"
top = "boreal_taiga_conifer_leaves"
bottom = "boreal_taiga_conifer_leaves"
side = "boreal_taiga_conifer_leaves"
