key = "rock_low_cluster_4x3"
texture = "exposed_rock"
material = "stone"
tint = [126, 124, 116, 255]

[[cuboids]]
x = 6
y = 0
z = 7
w = 3
h = 1
d = 2

[[cuboids]]
x = 9
y = 0
z = 8
w = 1
h = 1
d = 2

[[cuboids]]
x = 7
y = 1
z = 8
w = 2
h = 1
d = 1
